version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
      args:
        - DEV=true
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./server:/code
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=#kadfG834f+-sa
      - DB_HOST=db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=#kadfG834f+-sa
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
